### ISSUE TITLE
dart run wasm:setup fails on linux when referenced as a dependency pointing to git 

### ISSUE THREAD

**Issue by abner** [dart-lang/wasm#17]
I tried to reproduce the example on README on Ubuntu and it failed when i executed `dart run wasm:setup`.

I got this error:

```bash
...
manifest path `/home/abner/dart-wasm-project/.dart_tool/pub/bin/wasm/Cargo.toml` does not exist
```

I referenced the wasm project in my pubspec.yaml using git reference:

```
dependencies:
  wasm: 
    git:
      url: https://github.com/dart-lang/wasm.git
      ref: main
```

I manually copied the files in the wasm repository bin folder (Cargo.toml, finalizers.cc, setup.dart, wasmer.rs) into my `.dart_tool/pub/bin/wasm` and after it, the command `dart run wasm:setup` just worked.

Actually, i wanna also to know if dart-lang/wasm is intended to work inside Flutter apps (both mobile, desktop and web)?
